export const categoryPatterns = {
  'Leroy Merlin': 'Home / Renovation',
  'OBI': 'Home / Renovation',
  'Castorama': 'Home / Renovation',
  'McDonald': 'Eating out',
  'KOMAD': 'Eating out',
  'KFC': 'Eating out',
  'Caffee': 'Eating out',
  'Cafe': 'Eating out',
  'Coffee': 'Eating out',
  'Restauracja': 'Eating out',
  'Starbucks': 'Eating out',
  'Kebab': 'Eating out',
  'Bistro': 'Eating out',
  'Pizza': 'Eating out',
  'Lood': 'Eating out',
  'Falafel': 'Eating out',
  'Pizzeria': 'Eating out',
  'Kawiarnia': 'Eating out',
  'North Fish': 'Eating out',
  'Cukiernia': 'Eating out',
  'Prowizja wypłata gotówki': 'Bank fees',
  'Dropbox': 'Digital services',
  'Netfli': 'Digital services',
  'Google cloud': 'Digital services',
  'Youtube': 'Digital services',
  'Tauron': 'TO ACCOUNT FOR',
  'PGNIG': 'TO ACCOUNT FOR',
  'Zarządca sp. z o.o': 'TO ACCOUNT FOR',
  'Netia': 'TO ACCOUNT FOR',
  'UPC': 'Home / Utilities',
  'Transferwise': 'Business income',
  'Orange Polska': 'Phone',
  'Tesco': 'Shopping / Groceries',
  'Auchan': 'Shopping / Groceries',
  'Zabka': 'Shopping / Groceries',
  'Lidl': 'Shopping / Groceries',
  'Freshmarket': 'Shopping / Groceries',
  'Carrefour': 'Shopping / Groceries',
  'Buczek': 'Shopping / Groceries',
  'Awiteks': 'Shopping / Groceries',
  'Stokrotka': 'Shopping / Groceries',
  'Lewiatan': 'Shopping / Groceries',
  'Zieleniak': 'Shopping / Groceries',
  'Top market': 'Shopping / Groceries',
  'Biedronka': 'Shopping / Groceries',
  'Chleb': 'Shopping / Groceries',
  'Skarpa Bytom': 'Sport / Climbing',
  'Aldi': 'Shopping / Groceries',
  'Netto': 'Shopping / Groceries',
  'MPK': 'Transport / Tickets',
  'ZTM': 'Transport / Tickets',
  'Ikea': 'Home / Home stuff',
  'Revolut': 'Holidays',
  'BP': 'Transport / Fuel',
  'Lotos': 'Transport / Fuel',
  'Orlen': 'Transport / Fuel',
  'Shell': 'Transport / Fuel',
  'Autostrada': 'Transport / Road tolls',
  'Autopay': 'Transport / Road tolls',
  'Katowice Airport':  'Work-related',
  'CIRCLE K': 'Transport / Fuel',
  'emila': 'Transport / Fuel',
  'Izba Lekarska': 'Work-related',
  'Oil Kraków': 'Work-related',
  'C&A': 'Shopping / Clothes',
  'Reserved': 'Shopping / Clothes',
  'Urodziny': 'Shopping / Gifts',
  'Dentist': 'Healthcare',
  'Apteka': 'Healthcare',
  'Diagnostyka': 'Healthcare',
  'Google': 'Digital services',
  'homepl': 'Digital services',
  'Bilety SKM': 'Transport / Tickets',
  'Kolej': 'Transport / Tickets',
  'bilet': 'Transport / Tickets',
  'e-podroznik': 'Transport / Tickets',
  'Bluj': 'Home / Rent',
  'PKP': 'Transport / Tickets',
  'ROMA SC4': 'Eating out',
  'Rossmann': 'Shopping / Cosmetics',
  'Hebe': 'Shopping / Cosmetics',
  'food': 'Eating out',
  'Stalesia Krakow': 'Shopping / Clothes',
  'bar mleczny': 'Eating out',
  'Skycash': 'Transport / Tickets',
  'autobus': 'Transport / Tickets',
  'patronite': 'Donations',
  'efl': 'Transport / Car leasing',
  'traficar': 'Transport / Car rental'
};
